name: flutter_card_organizer
description: Flutter application to organize yugioh cards.

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  logging: ^0.11.4
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  tuple: ^1.0.3
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.0
  file_picker: ^2.0.13
  fluttertoast: ^7.1.1
  image: ^2.1.19
  path_provider: ^1.6.24
  dio: ^3.0.10  
  image_editor: ^0.7.3
  extended_image: ^1.3.0

  firebase_core: ^0.5.2
  firebase_ml_vision: ^0.9.9  


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.5
  built_value_generator: any
  build_runner: any
  freezed: ^0.12.2

flutter:
  uses-material-design: true